const defaultAvatarUrl = "https://avatars.githubusercontent.com/u/911921?v=4";

export const players = [
  {
    name: "Ankur Singh",
    slug: "ankur-singh",
    position: "Point Guard",
    teamId: "bulls",
    number: 33,
    avatar:
      "https://i.ibb.co/YjfZy6k/ankur-n.jpg",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Deepak Chandani",
    slug: "deepak-chandani",
    position: "Point Guard",
    teamId: "bulls",
    number: 33,
    avatar: "https://avatars.githubusercontent.com/u/15975603?v=4",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Hirdesh Paliwal",
    slug: "hirdesh-paliwal",
    position: "Point Guard",
    teamId: "bulls",
    number: 33,
    avatar:
      "https://i.ibb.co/jLRPyPX/hirdesh.jpg",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Shiv Sharma",
    slug: "shiv-sharma",
    position: "Shooting Guard",
    teamId: "bulls",
    number: 15,
    avatar: "https://avatars.githubusercontent.com/u/2811538?v=4",
    rpg: 5,
    spg: 2,
    apg: 4,
    ppg: 15,
  },
  {
    name: "Rajat Bansal",
    slug: "rajat-bansal",
    position: "Power Forward",
    teamId: "koalas",
    number: 14,
    avatar: "https://i.ibb.co/MMM90yK/rajat-bansal.jpg",
    rpg: 8,
    spg: 1,
    apg: 2,
    ppg: 10,
  },
  {
    name: "Raghu Raj",
    slug: "raghu-raj",
    position: "Power Forward",
    teamId: "koalas",
    number: 99,
    avatar: "https://i.ibb.co/VYxyyVP/raghu-n.jpg",
    rpg: 8,
    spg: 1,
    apg: 2,
    ppg: 10,
  },
  {
    name: "Bonnie Eisenman",
    slug: "bonnie-eisenman",
    position: "Center",
    teamId: "lemurs",
    number: 11,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/brindelle",
    rpg: 10,
    spg: 1,
    apg: 1,
    ppg: 10,
  },
  {
    name: "Gajendra Singh",
    slug: "gajendra-singh",
    position: "Point Guard",
    teamId: "foxes",
    number: 10,
    avatar: "https://avatars.githubusercontent.com/u/15975536?v=4",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Pradeep Korriya",
    slug: "pradeep-korriya",
    position: "Power Forward",
    teamId: "foxes",
    number: 13,
    avatar: "https://i.ibb.co/zrXxKvh/pradeep-korriya-n.jpg",
    rpg: 5,
    spg: 2,
    apg: 4,
    ppg: 15,
  },
  {
    name: "Vijay Jangid",
    slug: "vijay-jangid",
    position: "Shooting Forward",
    teamId: "foxes",
    number: 21,
    avatar: "https://avatars.githubusercontent.com/u/11829883?v=4",
    rpg: 6,
    spg: 2,
    apg: 3,
    ppg: 13,
  },
  {
    name: "Ashok Jangid",
    slug: "ashok-jangid",
    position: "Shooting Guard",
    teamId: "foxes",
    number: 22,
    avatar: "https://i.ibb.co/SsDYc9t/Ashok.jpg",
    rpg: 8,
    spg: 1,
    apg: 2,
    ppg: 10,
  },
  {
    name: "Richard Feldman",
    slug: "richard-feldman",
    position: "Center",
    teamId: "lemurs",
    number: 46,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/rtfeldman",
    rpg: 10,
    spg: 1,
    apg: 1,
    ppg: 10,
  },
  {
    name: "Rohan Julka",
    slug: "Rohan Julka",
    position: "Point Guard",
    teamId: "koalas",
    number: 32,
    avatar: "https://i.ibb.co/Czfprsf/rohan-n.jpg",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Sawan Kumar",
    slug: "sawan-kumar",
    position: "Shooting Forward",
    teamId: "koalas",
    number: 36,
    avatar: "https://avatars.githubusercontent.com/u/29453442?v=4",
    rpg: 6,
    spg: 2,
    apg: 3,
    ppg: 13,
  },

  {
    name: "Subodh Sharma",
    slug: "subodh-sharma",
    position: "Shooting Forward",
    teamId: "hedgehogs",
    number: 37,
    avatar: "https://i.ibb.co/fHdvzDJ/subodh.jpg",
    rpg: 6,
    spg: 2,
    apg: 3,
    ppg: 13,
  },
  {
    name: "Divyang Bhambhani",
    slug: "divyang-bhambhani",
    position: "Power Forward",
    teamId: "hedgehogs",
    number: 76,
    avatar: "https://i.ibb.co/qkhLmY2/divyang-n.jpg",
    rpg: 8,
    spg: 1,
    apg: 2,
    ppg: 10,
  },
  {
    name: "Mateusz Zatorski",
    slug: "mateusz-zatorski",
    position: "Center",
    teamId: "hedgehogs",
    number: 23,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/matzatorski",
    rpg: 10,
    spg: 1,
    apg: 1,
    ppg: 10,
  },
  {
    name: "Kyle Mathews",
    slug: "kyle-mathews",
    position: "Point Guard",
    teamId: "lemurs",
    number: 19,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/kylemathews",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Lin Clark",
    slug: "lin-clark",
    position: "Shooting Guard",
    teamId: "lemurs",
    number: 66,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/linclark",
    rpg: 5,
    spg: 2,
    apg: 4,
    ppg: 15,
  },
  {
    name: "Guillermo Rauch",
    slug: "guillermo-rauch",
    position: "Shooting Forward",
    teamId: "lemurs",
    number: 34,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/rauchg",
    rpg: 6,
    spg: 2,
    apg: 3,
    ppg: 13,
  },
  {
    name: "Val Head",
    slug: "val-head",
    position: "Shooting Forward",
    teamId: "bulls",
    number: 1,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/vlh",
    rpg: 6,
    spg: 2,
    apg: 3,
    ppg: 13,
  },
  {
    name: "Rach Smith",
    slug: "rach-smith",
    position: "Center",
    teamId: "lemurs",
    number: 55,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/rachsmithtweets",
    rpg: 10,
    spg: 1,
    apg: 1,
    ppg: 10,
  },
  {
    name: "Manish Khunteta",
    slug: "manish-khunteta",
    position: "Center",
    teamId: "koalas",
    number: 69,
    avatar:
      "https://i.ibb.co/xLnvy5Y/manish-n.jpg",
    rpg: 10,
    spg: 1,
    apg: 1,
    ppg: 10,
  },
  {
    name: "Tom Occhino",
    slug: "tom-occihino",
    position: "Point Guard",
    teamId: "koalas",
    number: 87,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/tomocchino",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Aimee Knight",
    slug: "aimee-knight",
    position: "Shooting Guard",
    teamId: "koalas",
    number: 26,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/Aimee_Knight",
    rpg: 5,
    spg: 2,
    apg: 4,
    ppg: 15,
  },
  {
    name: "Ean Platter",
    slug: "ean-platter",
    position: "Shooting Guard",
    teamId: "hedgehogs",
    number: 10,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/eanplatter",
    rpg: 5,
    spg: 2,
    apg: 4,
    ppg: 15,
  },
  {
    name: "Sophie Alpert",
    slug: "sophie-alpert",
    position: "Power Forward",
    teamId: "koalas",
    number: 54,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/sophiebits",
    rpg: 8,
    spg: 1,
    apg: 2,
    ppg: 10,
  },
];
