export const players = [
  {
    name: "Tyler McGinnis",
    slug: "tyler-mcginnis",
    position: "Point Guard",
    teamId: "bulls",
    number: 33,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/tylermcginnis",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Jared Palmer",
    slug: "jared-palmer",
    position: "Shooting Guard",
    teamId: "bulls",
    number: 15,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/jaredpalmer",
    rpg: 5,
    spg: 2,
    apg: 4,
    ppg: 15,
  },
  {
    name: "Val Head",
    slug: "val-head",
    position: "Shooting Forward",
    teamId: "bulls",
    number: 1,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/vlh",
    rpg: 6,
    spg: 2,
    apg: 3,
    ppg: 13,
  },
  {
    name: "Dan Abramov",
    slug: "dan-abramov",
    position: "Power Forward",
    teamId: "bulls",
    number: 99,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/dan_abramov",
    rpg: 8,
    spg: 1,
    apg: 2,
    ppg: 10,
  },
  {
    name: "Bonnie Eisenman",
    slug: "bonnie-eisenman",
    position: "Center",
    teamId: "bulls",
    number: 11,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/brindelle",
    rpg: 10,
    spg: 1,
    apg: 1,
    ppg: 10,
  },
  {
    name: "Kevin Lacker",
    slug: "kevin-lacker",
    position: "Point Guard",
    teamId: "foxes",
    number: 10,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/lacker",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Pete Hunt",
    slug: "pete-hunt",
    position: "Shooting Guard",
    teamId: "foxes",
    number: 13,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/floydophone",
    rpg: 5,
    spg: 2,
    apg: 4,
    ppg: 15,
  },
  {
    name: "Sarah Drasner",
    slug: "sarah-drasner",
    position: "Shooting Forward",
    teamId: "foxes",
    number: 21,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/sarah_edo",
    rpg: 6,
    spg: 2,
    apg: 3,
    ppg: 13,
  },
  {
    name: "Jed Watson",
    slug: "jed-watson",
    position: "Power Forward",
    teamId: "foxes",
    number: 22,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/JedWatson",
    rpg: 8,
    spg: 1,
    apg: 2,
    ppg: 10,
  },
  {
    name: "Richard Feldman",
    slug: "richard-feldman",
    position: "Center",
    teamId: "foxes",
    number: 46,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/rtfeldman",
    rpg: 10,
    spg: 1,
    apg: 1,
    ppg: 10,
  },
  {
    name: "Preethi Kasireddy",
    slug: "preethi-kasireddy",
    position: "Point Guard",
    teamId: "hedgehogs",
    number: 32,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/iam_preethi",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Ean Platter",
    slug: "ean-platter",
    position: "Shooting Guard",
    teamId: "hedgehogs",
    number: 10,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/eanplatter",
    rpg: 5,
    spg: 2,
    apg: 4,
    ppg: 15,
  },
  {
    name: "Sunil Pai",
    slug: "sunil-pai",
    position: "Shooting Forward",
    teamId: "hedgehogs",
    number: 37,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/threepointone",
    rpg: 6,
    spg: 2,
    apg: 3,
    ppg: 13,
  },
  {
    name: "Pam Selle",
    slug: "pam-selle",
    position: "Power Forward",
    teamId: "hedgehogs",
    number: 76,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/pamasaur",
    rpg: 8,
    spg: 1,
    apg: 2,
    ppg: 10,
  },
  {
    name: "Mateusz Zatorski",
    slug: "mateusz-zatorski",
    position: "Center",
    teamId: "hedgehogs",
    number: 23,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/matzatorski",
    rpg: 10,
    spg: 1,
    apg: 1,
    ppg: 10,
  },
  {
    name: "Kyle Mathews",
    slug: "kyle-mathews",
    position: "Point Guard",
    teamId: "lemurs",
    number: 19,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/kylemathews",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Lin Clark",
    slug: "lin-clark",
    position: "Shooting Guard",
    teamId: "lemurs",
    number: 66,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/linclark",
    rpg: 5,
    spg: 2,
    apg: 4,
    ppg: 15,
  },
  {
    name: "Guillermo Rauch",
    slug: "guillermo-rauch",
    position: "Shooting Forward",
    teamId: "lemurs",
    number: 34,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/rauchg",
    rpg: 6,
    spg: 2,
    apg: 3,
    ppg: 13,
  },
  {
    name: "Michael Chan",
    slug: "michael-chan",
    position: "Power Forward",
    teamId: "lemurs",
    number: 14,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/chantastic",
    rpg: 8,
    spg: 1,
    apg: 2,
    ppg: 10,
  },
  {
    name: "Rach Smith",
    slug: "rach-smith",
    position: "Center",
    teamId: "lemurs",
    number: 55,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/rachsmithtweets",
    rpg: 10,
    spg: 1,
    apg: 1,
    ppg: 10,
  },
  {
    name: "Tom Occhino",
    slug: "tom-occihino",
    position: "Point Guard",
    teamId: "koalas",
    number: 87,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/tomocchino",
    rpg: 3,
    spg: 4,
    apg: 8,
    ppg: 12,
  },
  {
    name: "Aimee Knight",
    slug: "aimee-knight",
    position: "Shooting Guard",
    teamId: "koalas",
    number: 26,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/Aimee_Knight",
    rpg: 5,
    spg: 2,
    apg: 4,
    ppg: 15,
  },
  {
    name: "Brian Holt",
    slug: "brian-holt",
    position: "Shooting Forward",
    teamId: "koalas",
    number: 36,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/holtbt",
    rpg: 6,
    spg: 2,
    apg: 3,
    ppg: 13,
  },
  {
    name: "Sophie Alpert",
    slug: "sophie-alpert",
    position: "Power Forward",
    teamId: "koalas",
    number: 54,
    avatar: "https://res.cloudinary.com/uidotdev/image/twitter_name/sophiebits",
    rpg: 8,
    spg: 1,
    apg: 2,
    ppg: 10,
  },
  {
    name: "Ken Wheeler",
    slug: "ken-wheeler",
    position: "Center",
    teamId: "koalas",
    number: 69,
    avatar:
      "https://res.cloudinary.com/uidotdev/image/twitter_name/ken_wheeler",
    rpg: 10,
    spg: 1,
    apg: 1,
    ppg: 10,
  },
];
